#!/usr/bin/env bash
set -euo pipefail

REPORT_FILE="${1:-}"
if [ -z "${REPORT_FILE}" ] || [ ! -f "${REPORT_FILE}" ]; then
  echo "Usage: $0 <path-to-report.md>"
  exit 1
fi

REPORT_DATE="$(basename "${REPORT_FILE}" .md)"
REPO_URL="https://github.com/${GITHUB_REPOSITORY}"
FILE_URL="${REPO_URL}/blob/${GITHUB_REF_NAME:-main}/${REPORT_FILE}"
RUN_URL="${REPO_URL}/actions/runs/${GITHUB_RUN_ID}"
PREVIEW="$(sed -n '1,80p' "${REPORT_FILE}")"

BODY_FILE="$(mktemp)"
cat > "${BODY_FILE}" <<EOF
## Raven Daily Content Plan · ${REPORT_DATE}

📄 **Full report:** [${REPORT_FILE}](${FILE_URL})

---

### Preview

${PREVIEW}

---

_Generated by GitHub Actions · [workflow run #${GITHUB_RUN_NUMBER}](${RUN_URL})_
EOF

gh label create "daily-content" --color "6f42c1" --description "Automated Raven daily content plan" 2>/dev/null || true

gh issue create \
  --title "📋 Daily Content Plan · ${REPORT_DATE}" \
  --label "daily-content" \
  --body-file "${BODY_FILE}"

rm -f "${BODY_FILE}"
